# general config
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g focus-events on
set -g history-limit 50000
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -sg escape-time 0
set -g set-clipboard on
set -g repeat-time 1000

# keybinds
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

unbind r
bind r source-file $HOME/.tmux.conf

bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

bind c new-window -a

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind = select-layout tiled

bind \; last-window

setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
# unbind -T copy-mode-vi MouseDragEnd1Pane
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"

bind o choose-tree -s -Z

# appearance

# colors from https://catppuccin.com/palette/
green="#a6e3a1"
yellow="#f9e2af"
peach="#fab387"
maroon="#eba0ac"
red="#f38ba8"
rosewater="#f5e0dc"
flamingo="#f2cdcd"
pink="#f5c2e7"
mauve="#cba6f7"
blue="#89b4fa"
teal="#94e2d5"
sky="#89dceb"
sapphire="#74c7ec"
text="#cdd6f4"
surface1="#45475a"
surface0="#313244"
base="#1e1e2e"
mantle="#181825"
crust="#11111b"

set -g status-position top
set -g pane-border-lines simple

set -g status-left-length 100
set -g status-style "fg=${green},bg=default"

set -g status-left "#[fg=${green},bg=default,bold][#S] "
# set -g window-status-current-format "#[fg=${green},bg=${surface0},bold,underscore]#I:#W#F"
set -g window-status-current-format "#[fg=${base},bg=${green},bold]#I:#W#F"
set -g window-status-separator "  "
set -g status-right "%l:%M%P %Z %a %b-%d-%y"

set -g message-style "fg=${green},bg=default,bold"
set -g mode-style "fg=${crust},bg=${flamingo}"

set -g pane-border-style "fg=${text}"
set -g pane-active-border-style "fg=${green}"

