#       󰀱 󰚑 󰂹 󰅏 󰆚 󰼁 󰚌 󰈸   󱓞 󱓟     󰄬  󰸞      
#  󱨎 󱁆 󰀵

palette = "catppuccin_mocha"
add_newline = true
command_timeout = 1000
format = """
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_status\
$aws\
$cmd_duration\
$status\
$line_break\
$os\
$username\
$hostname\
$directory\
$sudo\
$character"""

[kubernetes]
symbol = '󰀱 '
format = '[$symbol$context(:$namespace)]($style) '
disabled = false

[git_branch]
symbol = '󱁕 '
format = '[$symbol$branch(:$remote_branch)]($style)'
disabled = false

[git_commit]
format = ' [󰼁 $hash$tag]($style)'
only_detached = true
tag_disabled = false
tag_symbol = ' 󰓹 '
tag_max_candidates = 0
disabled = false

[git_state]
format = ' [$state($progress_current/$progress_total)]($style)'
disabled = false

[git_status]
format = '[$all_status$ahead_behind]($style) '
ahead = ''
behind = ''
diverged = ''
disabled = false

[aws]
symbol = '󰅟 '
expiration_symbol = '⛆'
format = '[$symbol($profile )(\($region\)) (\[$duration\] )]($style)'
disabled = false

[cmd_duration]
format = ' [$duration]($style) '
min_time = 3_000
show_milliseconds = true
disabled = false

[status]
format = '[$symbol$common_meaning$signal_name$maybe_int]($style) '
symbol = ' '
success_symbol = '[](bold green)'
not_executable_symbol = 'lol '
not_found_symbol = ' '
sigint_symbol = '󰜺 '
signal_symbol = ' '
recognize_signal_code = true
map_symbol = true
disabled = false

[os]
format = "[$symbol]($style)"
disabled = false

[os.symbols]
Macos = " "
Linux = "󰌽 "
Ubuntu = "󰌽 "
Unknown = "󰮯 "

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
truncation_length = 0
truncate_to_repo = false
# Catppuccin 'lavender'
style = "bold lavender"
read_only = ''
disabled = false

[sudo]
format = '$symbol($style)'
symbol = '󱕴 '
disabled = false

[shlvl]
format = '[$symbol$shlvl]($style)'
repeat = true
symbol = '❯'
repeat_offset = 1
threshold = 0
disabled = false

[character]
format = '$symbol '
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
disabled = false

# Theme: https://github.com/catppuccin/starship/blob/main/starship.toml
# palette tables should be last in the config ⚓️
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

